### ISSUE TITLE
Check for updates on demand vs. automatically

### ISSUE THREAD

**Issue by hiddenillusion** [EricZimmerman/Registry#1]
Would be nice to have the update check done on-demand vs. automatically once the application is run... didn't like having a pop-up tell me a new version was ready without me choosing to check

**Comment by EricZimmerman** [comment]
Which program? I'm removing auto updates from recmd and re

**Comment by hiddenillusion** [comment]
ah sorry, didn't realize there were multiple utils out of this repo - this instance it was Registry Explorer.

**Comment by EricZimmerman** [comment]
This is just the repository for the back end parser. RE is separate. the next release will remove auto updating
