### ISSUE TITLE
Plugins errors

### ISSUE THREAD

**Issue by jvaldezjr1** [EricZimmerman/Registry#10]
![image](https://user-images.githubusercontent.com/7658588/62251778-10db4e00-b3ae-11e9-85ca-8a4b1b09a2aa.png)

Hi Erik,

I'm getting errors with plugins not loading with ver 1.5 of Reg  Explorer. I've extracted the archive and kept everything in the same location that the archive created.

**Comment by EricZimmerman** [comment]
my guess is you used windows to unzip the file. this is why they are blocked.

delete the directory, then unzip with 7zip or winrar and the issue will go away. 

try that and let me know

**Comment by jvaldezjr1** [comment]
Yup, that worked, thanks Eric.
