### ISSUE TITLE
 how to add or remove a registered key or value offline

### ISSUE THREAD

**Issue by i2i8** [EricZimmerman/Registry#13]
Can you give an example of how to add or remove a registered key or value offline? Such as:
SystemOnDemand = new RegistryHiveOnDemand(MoGlobal.Mount + @"\Windows\System32\config\SYSTEM");
How do I add a key or value to it?
How do I remove a key or value from it?

**Comment by EricZimmerman** [comment]
you dont.

its not for that. this is a forensic minded parser, it has no capabilities to add or remove keys, nor will it.

it is purely for reading hives, including deleted keys and values.

**Comment by i2i8** [comment]
Thank you very much for your reply. Can you recommend a plugin for offline reading and writing to the registry? Thanks again.

**Comment by EricZimmerman** [comment]
i would think the windows api would have one. i dont know for sure tho. never had to do it

**Comment by i2i8** [comment]
Okay, thank you very sweet much. Thank you again.
