### ISSUE TITLE
Please create an empty repository for Registry Explorer issues and discussions

### ISSUE THREAD

**Issue by unforgettableid** [EricZimmerman/Registry#19]
Dear @EricZimmerman:

Hi!

Based on Appendix B of its user manual, I presume that Registry Explorer is probably closed-source freeware.

It turns out that there indeed is [a centralized place](https://github.com/EricZimmerman/Issues) to open issues regarding the tool.  However, for a while, I didn't notice this centralized place.  Instead, I tried searching for a Registry Explorer GUI repository, with no luck.

I wonder if you could please create a new GitHub repository (github.com/EricZimmerman/Registry Explorer), with no code in it, where issues and/or discussions can go?

This is done at:  https://github.com/new

I would suggest the following options:

Repository name:  RegistryExplorerGUI

Description:  Registry Explorer is a plugin-based forensic tool for viewing and searching through offline Registry hives. The plugins and the Registry parser are open-source, but the rest of the GUI is closed-source.  You may file issues here.

Discussions:  Allowed.  (You can enable discussions in "Settings").

A suggested README.md file for the repository is [here](https://github.com/EricZimmerman/Issues/issues/185).

**Comment by EricZimmerman** [comment]
this is the preferred place for GUI related stuff, so its centralized

https://github.com/EricZimmerman/Issues
