### ISSUE TITLE
Feature Request: Copy Value Path

### ISSUE THREAD

**Issue by JamesHabben** [EricZimmerman/Registry#2]
Could you add an option to the right click > copy > menu to copy the full path of the value? You have the copy path of the keys already.

**Comment by EricZimmerman** [comment]
try right clicking on the value and using the Value Summary option. it will include the path to the value and other details. does that work?

**Comment by EricZimmerman** [comment]
closing as this should be in there already. if not lemme know and ill add for v1 release of RE
