### ISSUE TITLE
string.IndexOf() requires a StringComparison

### ISSUE THREAD

**Issue by Genbox** [EricZimmerman/Registry#4]
On this line: https://github.com/EricZimmerman/Registry/blob/master/Registry/Cells/VKCellRecord.cs#L413
StringComparison.Ordinal is missing. This becomes apparent when running on Linux since string.IndexOf has different behavior due to the different interpretation of strings.

The IndexOf() in the code above returns "0" on Linux and "-1" on Windows. Adding StringComparison.Ordinal makes the comparison encoding independent.

**Comment by EricZimmerman** [comment]
This is fixed and will be in the next release
